name: samer
favicon: null
layout_spectrum: 0.76719
typography_spectrum: 0.07788
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Travel Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020401'
    - '#c2c5ca'
    - '#8291a4'
    - '#2f3032'
    - '#646d34'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
